exclude:
  - .circleci/
  - .jekyll-cache/
  - .vs/
  - bower_components/
  - config/
  - .bowerrc
  - .gitignore
  - .htaccess
  - .ruby-version
  - bower.json
  - Capfile
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
      title: "GoodCity.HK 好人好市 - Your quality donated items can help people in need."
