
version: 2

defaults: &defaults
  docker:
    - image: circleci/ruby:2.6
  working_directory: ~/www.goodcity

jobs:
  bundle_and_deploy:
    <<: *defaults
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle check --path=vendor/bundle || bundle install --deployment --jobs=4 --retry=3
      - run: |
          [ "$CIRCLE_BRANCH" == "live" ] && bundle exec cap production deploy || bundle exec cap staging deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - bundle_and_deploy:
          filters:
            branches:
              only: /^(master|live)$/
